[package]
name = "aoc"
version = "0.1.0"
authors = ["Caleb Everett <everett.caleb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
futures = "0.3.1"
